package JDBC;

import java.sql.*;
public class JDBCConnect {
    private String url = "jdbc:postgresql://localhost:5432/dp2023?user=vitalii&password=232323";
    private static Connection con;
    public JDBCConnect(){
        try {
            con = DriverManager.getConnection(this.url);
            this.createTable();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    private void createTable() throws SQLException {
        String sqlCreate = """
                CREATE TABLE IF NOT EXISTS manpads (
                  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  "name" varchar,
                  "weight" real,
                  "photo" varchar
                );
                """;

        Statement st = con.createStatement();
        st.execute(sqlCreate);
    }
    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Connection getCon() {
        return con;
    }

    public void setCon(Connection con) {
        con = con;
    }
    public void closeConnect(){
        try {
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
